import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,metrics,campaignInput,utmUrl,recordClick,recordConversion,validState,csv} from '../demo/model.mjs';
test('seed metrics and zero denominators',()=>{const s=initialState();assert.equal(s.campaigns.reduce((n,c)=>n+c.revenue_cents,0),218000);assert.equal(metrics({...s.campaigns[0],clicks:0,spend_cents:0}).roas,null);assert.ok(validState(s));});
test('retry does not inflate revenue and changed payload conflicts',()=>{const s=initialState(),c=s.campaigns[0];recordClick(s,c.id,'click1');recordConversion(s,'click1','order1',5000);assert.deepEqual(recordConversion(s,'click1','order1',5000),{replayed:true});assert.equal(c.revenue_cents,77000);assert.throws(()=>recordConversion(s,'click1','order1',4000));});
test('two events on one click count one converted click',()=>{const s=initialState(),c=s.campaigns[0];recordClick(s,c.id,'click1');recordConversion(s,'click1','order1',100);recordConversion(s,'click1','order2',200);assert.equal(c.conversions,14);assert.equal(c.converted_clicks,13);});
test('invalid destination rejected, owned UTM replaced and unrelated values retained',()=>{const v={...initialState().campaigns[0],destination:'https://example.com/p?x=1&utm_source=old#offer'};const url=new URL(utmUrl(campaignInput(v,'id')));assert.equal(url.searchParams.get('x'),'1');assert.equal(url.searchParams.get('utm_source'),'linkedin');assert.equal(url.hash,'#offer');assert.throws(()=>campaignInput({...v,destination:'javascript:alert(1)'},'id'));});
test('storage validation and CSV injection defense',()=>{assert.equal(validState({version:1,campaigns:[{}],clicks:[],events:[]}),false);const s=initialState();s.campaigns[0].name='=SUM(A1)';assert.ok(csv(s).includes("'=SUM(A1)"));});
test('missing click and negative revenue rejected',()=>{const s=initialState();assert.throws(()=>recordConversion(s,'missing','order',100));recordClick(s,s.campaigns[0].id,'click');assert.throws(()=>recordConversion(s,'click','order',-1));});
